service:
  update_interval: 10
  log_level: error
mqtt:
  broker: mqtt://192.168.1.10:1883
  user: admin
  password: password
  client_id: aircon
  topic_prefix: aircon
  auto_discovery_topic: homeassistant
  auto_discovery_topic_retain: false
  certificate_authority: ca.crt
  skip_cert_cn_check: true
  certificate_client: client.crt
  key-client: client.key
devices:
  - ip: 192.168.68.51
    mac: a043b0df6562
    name: Living Room Air Con
    port: 80
    temperature_unit: C